### ISSUE TITLE
Install question

### ISSUE THREAD

**Issue by greavette** [this-fifo/rendezvous#1]
Hello,

Thank you very much for making this project available.  You've done a great job on providing an easy way to stand up a jitsi.meet session and easily send an email to all members.

I'm very interested in installing this locally on my home server so my family and extended family can use it to create a video chat session.  Especially during these times where we need to stay at home I'd like to provide an easy way for my family to stay connected and I think Jitsi Meet with your project fits perfectly.

Although I'm not a developer  I do have a virtual environment setup at home and I have followed instructions to install Jitsi meet locally so I'm not afraid of Linux or the command line.  Could I ask for your assistance on how I would setup your project locally at home on my CentOS virtual machine?  Specifically I'm looking for the following:
Detailed steps on what to install on my Linux server (is CentOS 7 ok to use?)
What files need to be configured.
I have a Nextcloud system already installed locally that is used by family for file and photo sharing so I would use your project hosted locally on my home server as an external app on my Nextcloud.  This would mean that wouldn't need to the first step to send an email to start the room creation process.  I would prefer to have the user just fill out the form to send the email to the people they are inviting.

Thank you in advance for any advice you can provide for me.

**Comment by this-fifo** [comment]
Hey @greavette 👋

This project was done more to illustrate how one can go about creating their own application relying on those APIs, I would treat it more as a starter/template rather than a complete solution _(although it does do a nice job to cover the basics)_

To better help you I would need to first try to understand what is your end goal so I can best give you the direction you want here

If you wish to have a quick and easy secret shared room to connect with your family, the cheapest way to do that is just relying on meet.jit.si with a strong unique room name that you share only with your family members and then you guys can agree on a secret password to enter in the room as an additional security measure if desired

But if you are talking about having a video conference solution running under a private network that only your family members can access then it is a whole different challenge _(but very much possible)_

Let me try to walk through that using this project as an example:

rendezvous relies on servers under the hood for these two things:
- Email
- Video Conferencing

### Email
This piece is done through the convenient free-tier of the **Twilio SendGrid** API and the free-tier of **Zeit now** Node.js Serverless runtime

To get this working on a server you want to manage, you can look at **snowjs** https://github.com/snowjs/cli they provide a way to use the same abstraction of **zeit now** in your own instances rather than their cloud

If you don't want to have the lambda-like abstraction provided by **zeit now**, then you would need to modify the API piece to be more like a regular backend so you can deploy it _(I won't go in details here since it's out of scope)_

### Video Conferencing
This piece is done by relying on Jitsi's free public server hosted here: https://meet.jit.si/

The nice thing about Jitsi is that it is open source and it has all the tools you need to self host it yourself, you can find a lot of details about them in their community and github page, I suggest you start at:

- https://jitsi.org/
- https://github.com/jitsi
- https://github.com/jitsi/jitsi-meet/blob/master/doc/README.md
- https://community.jitsi.org/

These resources should have more detailed steps on how to self host their solution including docker ready images

### Conclusion
Based on what I think you want to achieve _(running a private network that offers video conferencing for your family)_ I think you should look into self-hosting **Jitsi** instead of **rendezvous** and look into their authentication mechanism to secure it or simply blocking/whitelist the url so that only your family members can access it

Have a nice weekend!

**Comment by greavette** [comment]
Hello @this-fifo , really appreciate you taking the time to answer my question!  Thank you!

Perhaps I misunderstood what rendezvous was with regards to Jitsi Meet.  Your explanation has helped me better define what I was hoping to do.

Really what I liked was the clean second page where a Subject, emails, message and room password were all on one page so it was easy for someone to setup a jitsi meet room with these details and easily send of the invite.  For my use case I suppose what I'm looking for is a webpage frontend to Jitsi.meet.  I could stand up my own Jitsi Server (which I have done to see if I could) but using a frontend web page with a unique room name is perhaps all we need.  I was thinking of skinning the page with our family name and from this one page anyone in the family could quickly setup what they need from this one page.  Yes Jitsi.Meet can do this as well.  I just liked to look and ease from one page.  And I was also thinking of hard coding into this page the email addresses into a drop down perhaps so that the younger family members could pick who they wanted to include and again easily setup a video conference call with their cousins.  

I had though that your work here on github was that front end site to use the public jitsi meet servers.  Now as I look into this further there is more involved with rendezvous and an api to connect to a free email service.  

Not sure if what I've described above is soemthing your git project would assist with or not.  Your comments or feedback are welcome.  

Thanks!

**Comment by this-fifo** [comment]
Ah, I see, in that case perhaps my other library might help you build that application better than **rendezvous** checkout https://github.com/this-fifo/jutsu 

It's essentially a simple React wrapper that lets you easily customize a frontend with the jitsi-meet client embedded and allows you to input your own jitsi server _(it is also what I used to build **rendezvous**)_

To illustrate an example I deployed a live demo here using github-pages:
https://this-fifo.github.io/jutsu/

The code inside the `/example` directory there is what renders that live demo. You could extend that to include all sorts of customization and deploy to github pages or your internal network so your family can access

Hope that is more helpful
